---
- name: get jwt for cloud-init
  hosts: localhost
  gather_facts: false
  tasks:
    - name: get jwt from opaal
      ansible.builtin.uri:
        url: "{{ lookup('ansible.builtin.env', 'OPAAL_URL') }}/token"
        method: GET
        return_content: true
      register: opaal_response
      no_log: true
    - name: extract token for deployment
      ansible.builtin.set_fact:
        cloud_init_jwt: "{{ (opaal_response.content | from_json).access_token }}"
      no_log: true

- name: securely push cloud-init jwt to nodes
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: wait for node ssh setup
      ansible.builtin.wait_for_connection:
        connect_timeout: 300
        delay: 30
        sleep: 5
        timeout: 300
  roles:
    - role: tpm_secrets
      vars:
        cloud_init_jwt: "{{ hostvars.localhost.cloud_init_jwt }}"
