---
 - name: check for tpm
   ansible.builtin.stat:
     path: /dev/tpm0
   register: tpm_path


 - name: check for context
   ansible.builtin.shell: tpm2_nvread -C o -s 2048 1
   when: tpm_path.stat.exists
   ignore_errors: true
   register: tpm_context

 - name: create tpm context
   ansible.builtin.shell: tpm2_nvdefine 1 -C o -s 2048 -a "ownerread|ownerwrite"
   when: 
     - tpm_path.stat.exists
     - tpm_context.rc != 0
 

 - name: write auth jwt 
   ansible.builtin.shell: echo {{ cloud_init_jwt }} | tpm2_nvwrite -Q 1 -C o -i-
   when:
     - tpm_path.stat.exists
   no_log: true

 - name: write secret to /var/run/cloud-init-jwt
   ansible.builtin.template:
     src: jwt.j2
     dest: /var/run/cloud-init-jwt
     mode: '0600'
     owner: root
     group: root
   when: tpm_path.stat.exists == false
   no_log: true

